# NOTE: Do not use 1e-6 format because this is reqognized as a string
# Framework Settings
# GPS with Velocity and Magnetometer Settings

# Framework Settings
pub_on_prop: true
use_ros_time_now: true
gps_ros_time_now: true
verbose: false
verbose_out_of_order: true
discard_ooo_prop_meas: false
cov_debug: false
pub_cov: false
use_common_gps_reference: true

use_pressure: false
publish_gps_enu: true
publish_baro_height: true

# Yaw initialization
use_magnetometer: false
enable_manual_yaw_init: false
yaw_init_deg: -30
auto_mag_init_samples: 30

# Ros Settings
use_tcpnodelay: true
bypass_init_service: false

pub_cb_buffer_size: 1
sub_imu_cb_buffer_size: 200
sub_sensor_cb_buffer_size: 1
pub_prop_divider: 4

# Sensor Settings (175Hz)
gyro_rate_noise: 7.9e-5
gyro_bias_noise: 1e-6
acc_noise: 1.714e-3
acc_bias_noise: 4.7e-5

# Core state covariance p,v,q,bw,ba
core_init_cov_p: [1,1,1]
core_init_cov_v: [1,1,1]
core_init_cov_q: [0.1218,0.1218,0.1218] #20degree
core_init_cov_bw: [0.0076,0.0076,0.0076]
core_init_cov_ba: [0.01,0.01,0.01]

# Pose1 Settings
pose1_pos_meas_noise: [0.5,0.5,1.0]
# pose1_pos_meas_noise: [0.5,0.5,0.5]
# pose1_pos_meas_noise: [1.0,1.0,1.0]
pose1_att_meas_noise: [0.1,0.1,0.1]
pose1_cal_p_ip: [0,0,0]
pose1_cal_q_ip: [1,0,0,0]
pose1_state_init_cov: [0.000000001,0.000000001,0.000000001,0.000000001,0.000000001,0.000000001]

# Pose2 Settings
pose2_pos_meas_noise: [0.0,0.0,0.0]
pose2_att_meas_noise: [0,0,0]
pose2_cal_p_ip: [0,0,0]
pose2_cal_q_ip: [1,0,0,0]
pose2_state_init_cov: [0.00001,0.00001,0.00001,0.00001,0.00001,0.00001]

# GPS Settings
# gps_pos_meas_noise: [1.0,1.0,1.0]
gps_pos_meas_noise: [0.1,0.1,0.1]
# gps_pos_meas_noise: [0.5,0.5,0.75]
gps_vel_meas_noise: [0.01,0.01,0.01]
gps_cal_ig: [0-0.25,0,0.21]
gps_state_init_cov: [0.000000001,0.000000001,0.000000001]

# Baro Settings
baro_meas_noise: 0.5
baro_cal_ip: [0,0,0]
baro_state_init_cov: [0.00001,0.00001,0.00001]
pressure_temp_K: 278.15
pressure_const_temp: false

# Magnetometer Settings
mag_normalize: true
mag_declination: 0.0 #degree
mag_meas_noise: [0.5,0.5,0.5]
mag_cal_im: [0, 0, 0] #degree
mag_state_init_cov: [0.3, 0.3, 0.3, 0.00000076,0.00000076,0.00000076] #v_wm q_im
