missions:

  mission_1:
    description: "TEMPLATE - template"
    filepaths:
      - "template/template.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]
  
  mission_2:
    description: "TEMPLATE - Takeoff, hover, land"
    filepaths:
      - "template/toland.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]
  
  mission_3:
    description: "TEMPLATE - Square 3mx3m"
    filepaths:
      - "template/square.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]

  mission_4:
    description: "TEMPLATE - Straight Line 5m"
    filepaths:
      - "template/line.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]