missions:

  number: 5

  mission_1:

    description: "T5"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_01.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_02.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_03.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_04.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_05.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_06.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_07.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_08.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_09.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T5/T5_10.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_2:

    description: "T6"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T6.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_3:

    description: "T7"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T7.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_4:

    description: "T8"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T8.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_5:

    description: "T9"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T9.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_6:

    description: "T10"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T10.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_7:

    description: "T11"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T11.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_8:

    description: "T12"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T12.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_9:

    description: "T13"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T13.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_10:

    description: "T14"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/bhp_test/T14.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]
