missions:

  number: 5

  mission_1:

    description: "T5"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T5.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T5.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T5.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T5.csv"
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T5.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_2:

    description: "T6"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T6.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_3:

    description: "T7"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T7.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_4:

    description: "T8"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T8.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_5:

    description: "T9"

    filepaths:
      - "/home/core/catkin_ws/src/amadee/amadee_bringup/trajectories/T9.csv"

    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "manual"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "manual"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]
