missions:

  mission_1:
    description: "Takeoff, hover, land"
    filepaths:
      - "dh/toland.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]

  mission_2:
    description: "Square 3x3 - Normal"
    filepaths:
      - "gps/square.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]

  mission_3:
    description: "Straight Line 5m"
    filepaths:
      - "gps/line.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]

  mission_4:
    description: "Straight Line 3m"
    filepaths:
      - "gps/line_short.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]

  mission_5:
    description: "Medium Line 25m"
    filepaths:
      - "gps/line_medium.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]

  mission_6:
    description: "Long Line 50m"
    filepaths:
      - "gps/line_long.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]

  mission_7:
    description: "Long Line 100m"
    filepaths:
      - "gps/line_superlong.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "continue"]
