missions:

  mission_1:
    description: "Takeoff, hover, land"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/toland.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "hold"]
      - ["lrf", "hold"]
      - ["optitrack", "land"]

  mission_2:
    description: "Square 3x3 - Normal"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/square.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "hold"]
      - ["lrf", "hold"]
      - ["optitrack", "land"]

  mission_3:
    description: "Square 3x3 - Failure"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/square.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "land"]
      - ["uwb", "hold"]
      - ["lrf", "hold"]
      - ["optitrack", "failure"]

  mission_4:
    description: "Straight Line 5m"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/line.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "land"]
      - ["uwb", "hold"]
      - ["lrf", "hold"]
      - ["optitrack", "land"]

  mission_5:
    description: "Straight Line 3m"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/line_short.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "land"]
      - ["uwb", "hold"]
      - ["lrf", "hold"]
      - ["optitrack", "land"]
