missions:

  mission_1:
    description: "Takeoff, hover, land"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/toland.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_2:
    description: "Square 3x3 - Normal"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/square.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_3:
    description: "Straight Line 5m"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/line.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_4:
    description: "Straight Line 3m"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/line_short.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_5:
    description: "Long Line 50m"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/line_long.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_6:
    description: "Long Line 100m"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/line_superlong.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "hold"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]
