missions:

  mission_1:
    description: "Takeoff, hover, land"
    filepaths:
      - "dh/toland.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]

  mission_2:
    description: "Square 3x3 - Normal"
    filepaths:
      - "dh/square.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]

  mission_3:
    description: "Square 3x3 - Failure"
    filepaths:
      - "dh/square.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "failure"]

  mission_4:
    description: "Straight Line 5m"
    filepaths:
      - "dh/line.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]

  mission_5:
    description: "Straight Line 3m"
    filepaths:
      - "dh/line_short.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["optitrack", "land"]
