missions:

  mission_1:
    description: "Takeoff, hover, land"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/dh/toland5.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_2:
    description: "Straight Line 5m (at 1.5m)"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/line.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["rtk_gps_1", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_3:
    description: "Straight Line 5m (at 5m)"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps_high/line5.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["rtk_gps_1", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_4:
    description: "Straight Line 5m (at 10m)"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps_high/line10.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["rtk_gps_1", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_5:
    description: "Medium Line 25m (at 1.5m)"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps/line_medium.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["rtk_gps_1", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_6:
    description: "Medium Line 25m (at 5m)"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps_high/line_medium5.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["rtk_gps_1", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]

  mission_7:
    description: "Medium Line 25m (at 10m)"
    filepaths:
      - "/home/core/catkin_ws/src/flightstack/flightstack_bringup/trajectories/gps_high/line_medium10.csv"
    entities_actions:
      - ["px4_gps", "land"]
      - ["rtk_gps_1", "land"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "continue"]
      - ["px4_bar", "continue"]
      - ["mission_cam", "continue"]
      - ["uwb", "continue"]
      - ["lrf", "hold"]
      - ["optitrack", "continue"]
