missions:

  mission_1:
    description: "Takeoff, hover, land"
    filepaths:
      - "/home/core/catkin_ws/src/bw2/bw2_bringup/trajectories/dh_test/toland.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "failure"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]

  mission_2:
    description: "UWB init test"
    filepaths:
      - "/home/core/catkin_ws/src/bw2/bw2_bringup/trajectories/dh_test/uwb_init_test.csv"
    entities_actions:
      - ["px4_gps", "continue"]
      - ["px4_imu", "failure"]
      - ["px4_mag", "hold"]
      - ["px4_bar", "hold"]
      - ["mission_cam", "failure"]
      - ["lsm9ds1", "continue"]
      - ["rtk_gps_1", "continue"]
      - ["rtk_gps_2", "continue"]
      - ["realsense", "hold"]
